In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection  import train_test_split
from numpy.linalg import norm
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.metrics import accuracy_score
from scipy.spatial.distance import euclidean

In [3]:
digits = load_digits() #loading digits dataset from sklearn

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=1)

In [5]:
class potential_functions(BaseEstimator, ClassifierMixin):
    def __init__(self, k):
        self.k = k
    def fit(self, X, y = None):
        self.X = X
        self.y = y
    def F(self, d):
        return  1 / (d + 1)
    def predict(self, X):
        predictions = list()
        for x in X:
            distances = list()
            for i in range(0,len(self.X)):
                distances.append([euclidean(x, self.X[i]), self.y[i], 1 / euclidean(x, X_train[i]) + 1]) 
            distances.sort()
            weights = [0]*len(set(self.y))
            for i in range(self.k):
                weights[int(distances[i][1])] += distances[i][2]
            predictions.append(weights.index(max(weights)))
        return predictions
    def PE(self, X, y, eps):
        gamma = [0]*len(y)
        y_1 = [0]*len(y)
        y_1 = self.predict(X)
        print(accuracy_score(y,y_1))
        if (accuracy_score(y,y_1) < eps):
            for i in range(len(gamma)):
                if (y_1[i] != y[i]):
                    gamma[i] += 1
                else:
                    gamma[i] = y_1[i]                      
        return gamma
            

In [6]:
potential_functions = potential_functions(k=3)

In [7]:
potential_functions.fit(X_train, y_train)

In [8]:
gamma = potential_functions.PE(X_test, y_test, 1.0)

0.9848484848484849


In [9]:
from scipy.spatial.distance import euclidean
def predict_LW3(X_test, X_train, y_train, k):
    predictions = list()
    for x in X_test:
        distances = list()
        for i in range(0,len(X_train)):
            distances.append([euclidean(x, X_train[i]), y_train[i], 1 / euclidean(x, X_train[i]) + 1]) 
        distances.sort()
        weights = [0]*len(set(y_train))
        for i in range(k):
            weights[int(distances[i][1])] += distances[i][2]
        predictions.append(weights.index(max(weights)))
    return predictions

In [10]:
k = 3
predictions = predict_LW3(X_test, X_train, y_train, k)
LW3_matrix = confusion_matrix(y_test, predictions)

In [11]:
pe_matrix = confusion_matrix(y_test, gamma)

In [12]:
print("Confusion Matrix from LW3:\n", LW3_matrix)
print("Confusion Matrix from LW4:\n", pe_matrix)
print("Difference between them:\n", LW3_matrix - pe_matrix)

Confusion Matrix from LW3:
 [[63  0  0  0  0  0  0  0  0  0]
 [ 0 58  0  0  0  1  0  0  0  0]
 [ 0  0 54  0  0  0  0  1  0  0]
 [ 0  0  0 68  0  0  0  0  0  0]
 [ 0  0  0  0 66  0  0  0  0  0]
 [ 0  0  0  0  0 51  0  0  0  1]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  0  0  0 61  0  1]
 [ 0  1  0  0  0  0  0  0 50  0]
 [ 0  1  0  1  0  1  0  0  1 60]]
Confusion Matrix from LW4:
 [[63  0  0  0  0  0  0  0  0  0]
 [ 0 59  0  0  0  0  0  0  0  0]
 [ 0  1 54  0  0  0  0  0  0  0]
 [ 0  0  0 68  0  0  0  0  0  0]
 [ 0  0  0  0 66  0  0  0  0  0]
 [ 0  1  0  0  0 51  0  0  0  0]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  1  0  0  0  0  0 61  0  0]
 [ 0  1  0  0  0  0  0  0 50  0]
 [ 0  4  0  0  0  0  0  0  0 60]]
Difference between them:
 [[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  1  0  0  0  0]
 [ 0 -1  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0

In [13]:
accuracy_score(y_test, gamma)

0.9865319865319865